### ISSUE TITLE
firefox and waybar switch to default cursor

### ISSUE THREAD

**Issue by shot-codes** [Jappie3/hyprcursor-phinger#4]
I've installed on nixos with hm; When my cursor moves in front of a firefox window, or over waybar, it reverts to the default cursor.

**Comment by Jappie3** [comment]
That's a GTK problem, see https://wiki.hyprland.org/Hypr-Ecosystem/hyprcursor/#important-notes.
Basically some applications (for example GTK, the graphical toolkit used in e.g. Firefox & Waybar) don't support server-side cursors, thus Hyprcursor can't be used for them.

I think you can solve this by also installing Phinger cursors as an XCursor theme... Now that I think about it, that functionality could be implemented into this hm module, I'll take a look at it one of these days ^^

**Comment by shot-codes** [comment]
It would be much appreciated. I have tried installing the xcursor theme from the original repo with home manager with the following, but no luck:
```nix
{pkgs, ...}: {
  home.packages = [pkgs.glib];

  gtk = {
    enable = true;
    theme = {
      name = "Materia-dark-compact";
      package = pkgs.materia-theme;
    };
    cursorTheme = {
        name = "phinger-cursors";
        package = pkgs.phinger-cursors;
        size = 24;
    };
  };

  dconf.settings."org/gnome/desktop/interface" = {
    color-scheme = "prefer-dark";
    gtk-theme = "Materia-dark-compact";
  };
}
```
```nix
{
  inputs,
  pkgs,
  ...
}: {
  imports = [
    inputs.hyprcursor-phinger.homeManagerModules.hyprcursor-phinger
  ];
  programs.hyprcursor-phinger.enable = true;

  home.pointerCursor = {
    name = "phinger-cursors";
    package = pkgs.phinger-cursors;
    size = 32;
    gtk.enable = true;
    x11.enable = true;
  };
}
```

**Comment by Jappie3** [comment]
Looking into this a little more, home-manager already has modules for xcursor themes, so I don't think I'll be adding that functionality to this repo. I can set the correct xcursor theme for GTK (firefox, waybar, etc.) using the following:

```nix
pointerCursor = {
  package = pkgs.phinger-cursors;
  name = "phinger-cursors-light";
  size = 24;
  gtk.enable = true;
};
```

I think you were missing `-light` or `-dark` for the `name` attribute under `home.pointerCursor` @shot-codes

**Comment by shot-codes** [comment]
Thanks, adding the suffix did the trick :)
